FROM cristian0/webapp:latest
MAINTAINER Cristiano <cristiano@eboox.it>

#RUN curl -o /usr/bin/modman https://raw.github.com/colinmollenhour/modman/master/modman && chmod +x /usr/bin/modman 
RUN curl -o n98-magerun.phar https://raw.githubusercontent.com/netz98/n98-magerun/master/n98-magerun.phar && chmod +x ./n98-magerun.phar && cp ./n98-magerun.phar /usr/local/bin/
